 
version: '2'
services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vehicle
      MYSQL_USER: searqui
      MYSQL_PASSWORD: arquisoft
    ports:
      - "3307:3306"
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ".:/try5"
    ports:
      - "3001:3000"
    depends_on:
      - db
    links:
      - db
    environment:
      DB_USER: root
      DB_NAME: vehicle
      DB_PASSWORD: password
      DB_HOST: db